name: turtle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.3
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  http: ^0.13.4
  photo_view: ^0.14.0
  image_picker: ^0.8.5+3
  qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0

dependency_overrides:
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/